# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: horse.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Horse" do
    optional :name, :string, 1
    optional :birthday, :string, 2
    optional :sex, :string, 3
    optional :sire, :string, 4
    optional :mare, :string, 5
  end
end

Horse = Google::Protobuf::DescriptorPool.generated_pool.lookup("Horse").msgclass
